### ISSUE TITLE
BlueX versions modification

### ISSUE THREAD

**Issue by ttomovcik** [ttomovcik/BlueX#1]
BlueX versions (0.5 and 0.6) are going to be deleted from source

**Comment by ttomovcik** [comment]
All previous versions will be archived after uploading new 1.0a version! (src/old/archived)
New version will be in (src/new/multi/1.0a)

**Comment by CloudNineBobor** [comment]
RIP BlueX 0.1-0.9, but happy to 1.0 ! GLGL in next versions píčo ! ^^

2016-01-14 14:22 GMT+01:00 Tomáš Tomovčík <notifications@github.com>:
